CREATE TABLE USUARIO
(
    ID       SERIAL PRIMARY KEY,
    NOMBRE   VARCHAR(32),
    APELLIDO VARCHAR(32),
    ROL      INTEGER,
    SESION   BOOLEAN,
    ACTIVO   BOOLEAN,
    PASSWD   VARCHAR(256)
);

CREATE TABLE ROL
(
    ID     SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(256) UNIQUE
);

CREATE TABLE ESTUDIANTE
(
    ID              SERIAL PRIMARY KEY,
    NOMBRE          VARCHAR(32),
    APELLIDO        VARCHAR(32),
    CARNE_MINORIDAD VARCHAR(9),
    DIRECCION       VARCHAR(256),
    NACIMINETO      DATE,
    FIJO            VARCHAR(32),
    MOVIL           VARCHAR(32),
    ID_CENTRO       INTEGER,
    NOMBRE_PADRE    VARCHAR(32),
    NOMBRE_MADRE    VARCHAR(32)
);

CREATE TABLE CENTRO
(
    ID           SERIAL PRIMARY KEY,
    DESCRIPCION  VARCHAR(256),
    ID_MUNICIPIO INTEGER
);

CREATE TABLE MATERIA
(
    ID          SERIAL PRIMARY KEY,
    DESCRIPCION VARCHAR(256) UNIQUE
);

CREATE TABLE REGISTRO
(
    ANNIO         INTEGER,
    CICLO         INTEGER,
    ID_ESTUDIANTE INTEGER,
    ID_MATERIA    INTEGER,
    NOTA          REAL
);

CREATE TABLE MUNICIPIO
(
    ID          SERIAL PRIMARY KEY,
    DESCRIPCION VARCHAR(256) UNIQUE
);

ALTER TABLE USUARIO
    ADD CONSTRAINT FK_ROL FOREIGN KEY (ROL) REFERENCES ROL (ID);

ALTER TABLE ESTUDIANTE
    ADD CONSTRAINT FK_CENTRO FOREIGN KEY (ID_CENTRO) REFERENCES CENTRO (ID);

ALTER TABLE CENTRO
    ADD CONSTRAINT FK_MUNICIPIO FOREIGN KEY (ID_MUNICIPIO) REFERENCES MUNICIPIO (ID);

ALTER TABLE REGISTRO
    ADD CONSTRAINT PK_REGISTRO PRIMARY KEY (ANNIO, CICLO, ID_ESTUDIANTE, ID_MATERIA);

ALTER TABLE REGISTRO
    ADD CONSTRAINT FK_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTE (ID);

ALTER TABLE REGISTRO
    ADD CONSTRAINT FK_MATERIA FOREIGN KEY (ID_MATERIA) REFERENCES MATERIA (ID);

-- DATOS PARA ROL
INSERT INTO ROL (NOMBRE)
VALUES ('ADMINISTRADOR'),
       ('COORDINADOR');

-- DATOS PARA USUARIO
INSERT INTO USUARIO (NOMBRE, APELLIDO, ROL, SESION, ACTIVO, PASSWD)
VALUES ('JOSE', 'PINEDA', 1, FALSE, TRUE, '9aae0240e0e02983a5462a4914fe6bc3db91d41ff9a36b4ff22bc06e38e11628'),
       -- Pw : Pikachu1
       ('RAUL', 'HERRERA', 2, FALSE, TRUE, '6484e7fe84f02520350861bcf8d052590cc332de2465049e37e1f87232bdea5e'),
       -- Pw : Pikachu2
       ('ANDRES', 'PEREZ', 2, FALSE, TRUE, '40576429e7d72bf17dbcc4fa1f8d2faf9ad0ceb50bbff41b5a50da9963e271d3');
       -- Pw : Pikachu3

-- DATOS PARA MUNICIPIO

-- DATOS PARA CENTROS

-- DATOS PARA MATERIA

-- DATOS PARA ESTUDIANTE

